### PR TITLE
Fix multiple plot tabs shown when codebase is updated

### LINKED ISSUE #1205: [Bug, plots] When I re-save any py files, it auto-pops up new plots
**Describe the bug**

In one console, I have `pdr sim_plots` running. Since I've got it going, it's popped a plot window into my browser (good).

Then if I make any changes to any py file, it will open a _new_ plot window in my browser. This is annoying. It shouldn't open a new plot window. It should simply refresh the current one.

Related: 
- the following issue was recently completed: [#1144](https://github.com/oceanprotocol/pdr-backend/issues/1144) "[Sim_plots, UX] When 'pdr sim_plots' is run, it should automatically pop into browser"
- before it, we didn't have the problem that _this_ issue describes
- but after that issue was done, now the plots are over-zealous
- what we want is a happy medium: it should automatically pop _one_ plot into the browser, but not more

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #1205

### CODE REVIEW

**Comment by trentmc** [comment]
### Traceback from branch

It fails on launch. Traceback:
```text
(venv) trentmc@trents-m3: ~/code/pdr-backend $ pdr sim_plots
2024-06-13 20:55:59,034 cli INFO pdr None: Begin
2024-06-13 20:55:59,034 cli INFO Arguments:
2024-06-13 20:55:59,034 cli INFO debug_mode=False
2024-06-13 20:55:59,034 cli INFO run_id=None
2024-06-13 20:55:59,034 cli INFO port=8050
2024-06-13 20:55:59,034 cli INFO Nested args: {}
Dash is running on http://127.0.0.1:8050/

2024-06-13 20:55:59,101 dash.dash INFO Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'pdr_backend.sim.sim_dash'
 * Debug mode: off
2024-06-13 20:55:59,103 werkzeug INFO WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
2024-06-13 20:55:59,103 werkzeug INFO Press CTRL+C to quit
2024-06-13 20:55:59,110 pdr_backend.sim.sim_dash ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/dash/dash.py", line 1412, in _setup_server
    _validate.validate_layout(self.layout, self._layout_value())
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/dash/_validate.py", line 449, in validate_layout
    _validate(layout_value)
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/dash/_validate.py", line 438, in _validate
    _validate_id(component)
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/dash/_validate.py", line 428, in _validate_id
    raise exceptions.DuplicateIdError(
dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `pdr_profit_vs_time`
2024-06-13 20:55:59,112 werkzeug INFO 127.0.0.1 - - [13/Jun/2024 20:55:59] "GET / HTTP/1.1" 500 -
2024-06-13 20:55:59,199 werkzeug INFO 127.0.0.1 - - [13/Jun/2024 20:55:59] "GET /favicon.ico HTTP/1.1" 200 -
```

### Status quo
Traceback from main branch. This works.
```text
^C(venv) trentmc@trents-m3: ~/code/pdr-backend $ pdr sim_plots
2024-06-13 20:58:36,493 cli INFO pdr None: Begin
2024-06-13 20:58:36,493 cli INFO Arguments:
2024-06-13 20:58:36,493 cli INFO run_id=None
2024-06-13 20:58:36,493 cli INFO port=8050
2024-06-13 20:58:36,493 cli INFO Nested args: {}
Dash is running on http://127.0.0.1:8050/

2024-06-13 20:58:36,565 dash.dash INFO Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'pdr_backend.sim.sim_dash'
 * Debug mode: on
2024-06-13 20:58:37,834 cli INFO pdr None: Begin
2024-06-13 20:58:37,834 cli INFO Arguments:
2024-06-13 20:58:37,834 cli INFO run_id=None
2024-06-13 20:58:37,834 cli INFO port=8050
2024-06-13 20:58:37,834 cli INFO Nested args: {}
```

**Review by trentmc — CHANGES_REQUESTED** [review]
It's breaking, see comment

**Comment by KatunaNorbert** [comment]
Interesting, wondering how we didn't encounter that before it's not introduced in this PR, but I found the fix.
Also found something on the arima plots side which I'm looking into next.

**Comment by KatunaNorbert** [comment]
I see, the arima issue was fixed here #1206

**Review by trentmc — APPROVED** [review]

**Pull request merged**
