### PR TITLE
Issue991 - get duckdb pr up-to-date with main

### LINKED ISSUE #991: [duckdb][integration] Get branch updated to work w/ main
### Background / motivation

There are a handful of tests failing.
Get duckdb pr up-to-date with main.

### TODOs / DoD
- [ ] Duckdb pr has main integrated

### PR DESCRIPTION
**Pull request by idiom-bytes**
Fixes #991

Changes proposed in this PR:
- [x] Get tests, linting, formatting, etc... all passing
- [x] There are roughly 15 tests failing

### CODE REVIEW

**Comment by calina-c** [comment]
@idiom-bytes I thought I'd help with this :) I did basic fixes, but in test_table I removed some stuff that seemed stale from a previous iteration: the testing of some inexistent functions on Table class. If that is not correct, please revert that commit.

**Comment by calina-c** [comment]
very interestingly, the last failing test remaining in the CI... does not fail for me locally.

**Comment by idiom-bytes** [comment]
Similar to calina, "everything works locally" but then fails on the CICD 

Tried to run workflows locally using github cli cliet & `gh act`, however, I'm having difficulties getting that to work.

**Comment by idiom-bytes** [comment]
setup_data and polars filter are being used as a fixture for a lot of the `test_etl_coverage` so we have a "known, consistent test fixture" to work with. I don't know why this didn't become an issue earlier.
```
@pytest.fixture
def setup_data(
    _gql_datafactory_etl_payouts_df,
    _gql_datafactory_etl_predictions_df,
    _gql_datafactory_etl_truevals_df,
    _gql_datafactory_etl_slots_df,
    _get_test_PDS,
    tmpdir,
    request,
):
    st_timestr = request.param[0]
    fin_timestr = request.param[1]

    preds = get_filtered_timestamps_df(
        _gql_datafactory_etl_predictions_df, st_timestr, fin_timestr
    )
    truevals = get_filtered_timestamps_df(
        _gql_datafactory_etl_truevals_df, st_timestr, fin_timestr
    )
    payouts = get_filtered_timestamps_df(
        _gql_datafactory_etl_payouts_df, st_timestr, fin_timestr
    )
    slots = get_filtered_timestamps_df(
        _gql_datafactory_etl_slots_df, st_timestr, fin_timestr
    )
```

**Comment by idiom-bytes** [comment]
As @calina-c fixed a lot of he issues, including the CICD, I am marking this as completed so we can merge it although we did not have a github-worthy review.

**Comment by idiom-bytes** [comment]
As discussed, we weer working towards fixing this 1 issue to be able to merge this PR.
Thank you @calina-c!

**Pull request merged**
