### PR TITLE
For #631 Black, pylint and mypy have errors locally, but pass in CI

### PR DESCRIPTION
**Pull request by trentmc**
This is a PR for #631.

So far, this PR has just 1 commit: the changes that were auto-performed by Trent's local black. However, that makes remote CI complain. Something's up...

### CODE REVIEW

**Comment by calina-c** [comment]
@trentmc I talked about this. You need to do an upgrade of black locally, since yours is probably outdated now. Probably a pip upgrade too, if black upgrade doesn't fix it.

**Comment by calina-c** [comment]
@trentmc I also have those in pylint, not sure what the difference is, I was used to just ignoring the ones that only show up locally as a config thing. Let's update the issue to reflect just the pylint misalignment, drop this PR and please assign me to the issue. I'll take a look when I finish needling in the time types.

**Comment by trentmc** [comment]
Thanks @calina-c. I just created a new github issue for the specific pylint failures: [#644](https://github.com/oceanprotocol/pdr-backend/issues/644). Therefore I can close _this_ issue and PR.

**Comment by trentmc** [comment]
> [@calina-c wrote] drop this PR and please assign me to the issue

Done - in the new issue [#644](https://github.com/oceanprotocol/pdr-backend/issues/644)

**Pull request closed without merging**
