### PR TITLE
Fix #1248: Merge Process: Pick Lake Improvements the PR-1129

### LINKED ISSUE #1248: [Lake] Merge Process: Pick Lake Improvements the PR-1129
**Definition of Done (DoD):**

- Take the lake improvements from PR-1129 using cherry-pick (or manually). Resolve conflicts and ensure everything works correctly.

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #1248 

Changes proposed in this PR:

- picking changes from the PR-1129 (thanks to @calina-c ) because of the git history change after the duckdb merge process
- conflict fix

We can close the PR-1129 when we merge this one

### CODE REVIEW

**Comment by calina-c** [comment]
@kdetry will you iterate with Roberto for the tables and keys to display? I'm fine with having just one owner of this issue.

**Comment by kdetry** [comment]
> @kdetry will you iterate with Roberto for the tables and keys to display? I'm fine with having just one owner of this issue.

@calina-c I have informed Roberto, he said they will complete it so it is on them after that

**Comment by kdetry** [comment]
@idiom-bytes

**Comment by idiom-bytes** [comment]
@kdetry Im just noticing you tagging me on this PR now... as far as I know, all of this has already been merged and the issue has been closed

can you close this?

**Comment by kdetry** [comment]
Changes are merged already, we can ignore it.

**Pull request closed without merging**
