### PR TITLE
Fix #1572: extra columns and sorting

### LINKED ISSUE #1572: [PdrDashboard] Homepage Tables Improvements
- [ ] Add more columns to home page feeds table:
- - Avg Accuracy
- - Sales 
- [ ] fix column sorting for both tables

### PR DESCRIPTION
**Pull request by kdetry**
Fixes #1572 . it is a draft yet

### CODE REVIEW

**Review by kdetry — COMMENTED** [review]
After passing pylint checks and tests, we can merge it.

**Comment by KatunaNorbert** [comment]
I'm noticing some issues here:
- sorting on feeds table is not working, nothing happens on the table when I try to sort
- whenever I sort, the payout queries are triggered and charts are rerenderd which we don't want
- after a few sorts, I run into this error which crushes the app:
Screenshot 2024-09-05 at 16 20 39

**Comment by kdetry** [comment]
Disabled sorting on the homepage and solved conflicts

**Comment by KatunaNorbert** [comment]
I'm still running into some strange issues, such as UI stuck in loading:
Screenshot 2024-09-10 at 09 53 48

What I suggest is if we disable sorting also remove all the changes related to sorting added to this branch, there is no need it add in those changes which might impact other parts if we are disabling the sorting

**Comment by kdetry** [comment]
These fixes moved and completed to the following PR:

https://github.com/oceanprotocol/pdr-backend/pull/1597

**Pull request closed without merging**
