### PR TITLE
Fix #1174: Can't launch ARIMA plots // BoxCox unstable

### LINKED ISSUE #1174: [Bug, ARIMA plots] Can't launch ARIMA plots // BoxCox unstable
### Describe the bug

I went to launch ARIMA plots. In console:
```console
pdr arima_plots my_ppss.yaml 
```

I got two errors:
Screenshot 2024-06-10 at 10 11 10

And the app can't successfully launch.

### Bug 1 detail
Screenshot 2024-06-10 at 10 11 47

Text version:
```text
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/pdr_backend/aimodel/dash_plots/callbacks.py", line 202, in create_transition_chart
    files_data[feed_data],
TypeError: 'NoneType' object is not subscriptable
```

### Bug 2 detail
Screenshot 2024-06-10 at 10 12 19
Screenshot 2024-06-10 at 10 12 24

Text version:
```text
Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'close'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/trentmc/code/pdr-backend/pdr_backend/aimodel/dash_plots/callbacks.py", line 42, in read_from_file
    data = read_files_from_directory(files_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/pdr_backend/aimodel/dash_plots/util.py", line 18, in read_files_from_directory
    "close_data": df["close"],
                  ^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/trentmc/code/pdr-backend/venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'close'
```

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #1174.

### CODE REVIEW

**Review by trentmc — CHANGES_REQUESTED** [review]
I have the same errors as before.

**Comment by KatunaNorbert** [comment]
Hm.. trying to reproduce it, the other case that gives this errors is if you have the data but the data is doesn't contain the required fields: `close, timestamp`. Could you check if this is the case?

**Comment by trentmc** [comment]
> Hm.. trying to reproduce it, the other case that gives this errors is if you have the data but the data is doesn't contain the required fields: close, timestamp. Could you check if this is the case?

I decided to do a clean repo and get clean data.

Then the error went away.

Now I have another error: in autocorrelation_plotter.py, the the output of `stats.boxcox(y)` gives a constant value of `y_bc`, which then makes the next line call to `adfuller(y_bc)` to fail. 

This is a numerical issue / maybe a bug in stats library. There might be a workaround. [Ref](https://github.com/scipy/scipy/issues/6873). 

I'll dig into this. Therefore: I will take the issue from here. I'll pass the issue / PR back to you if appropriate.

**Comment by trentmc** [comment]
I got it working now. The problem was that stats.boxcox() was unstable. So I introduced a new function safe_boxcox().

I will merge when tests pass.

**Comment by trentmc** [comment]
My test data was 5050 historical BTC candles. 

Here's the original distribution:
original

Here's the (safely) transformed distribution:
Screenshot 2024-06-10 at 13 13 52

Here's the ARIMA feed plots, now that they're working.
(The left plot has issues, I reported that in [#1180](https://github.com/oceanprotocol/pdr-backend/issues/1180).)
Screenshot 2024-06-10 at 13 02 46

**Pull request merged**
